# Generated by Django 3.0.4 on 2020-11-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('span', models.CharField(max_length=5)),
                ('amount', models.IntegerField()),
                ('received_datetime', models.DateTimeField()),
                ('mode', models.CharField(max_length=10)),
            ],
        ),
    ]
