# Generated by Django 3.0.4 on 2020-10-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.CharField(max_length=30)),
                ('topic', models.CharField(max_length=60)),
                ('homework', models.CharField(max_length=60)),
                ('brought_over', models.CharField(max_length=60)),
                ('remarks', models.CharField(max_length=100)),
                ('payout', models.IntegerField()),
            ],
        ),
    ]
