# Generated by Django 3.0.4 on 2020-10-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_class_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='brought_over',
            field=models.CharField(default='No', max_length=60),
        ),
        migrations.AlterField(
            model_name='class',
            name='homework',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AlterField(
            model_name='class',
            name='remarks',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
